/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Logo: React.FC = () => {
  return (
    <div className={"logoWrapper"}>
      <div className={"logoMain"}>
        <div className={"logoIconWrapper"}>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/76b74c584bbf0fa70b79ba811eed05ae0dcedfce4be16c55021e2a2f1a95bdd4?placeholderIfAbsent=true&apiKey=ec77cbb3cd35477ead1cb38ab83dc66b"
            className={"logoIcon"}
            alt=""
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/e296c0f3f1125bcec9cfa49a4c66fec7e089465e8d5c88213d206f4d82d94b0f?placeholderIfAbsent=true&apiKey=ec77cbb3cd35477ead1cb38ab83dc66b"
            className={"logoIcon2"}
            alt=""
          />
        </div>
        <h1 className={"logoText"}>Chroma Explorer</h1>
      </div>
    </div>
  );
};

export default Logo;
