# This is a basic workflow to help you get started with Actions

name: Continuous build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [main]

jobs:
  # This workflow contains a two job called "build" and "slacknotification"
  build:
    # The type of runner that the job will run on
    name: Build and Test
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Setup Node version 22
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose        

      - name: Run tests
        run: npm run test

      - name: Run playwright tests
        run: npm run playwright        

