name: Merge Continuous build

# Controls when the action will run.
on:
  pull_request:
    types: [closed]

  push:
    branches: [main]

jobs:
  build:
    
    if: github.event.pull_request.merged == true
    # The type of runner that the job will run on
    name: Main Build and Test
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose  
          
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium          
          
      - name: Setup Node version 22
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build 

      - name: Run tests
        run: npm run test

      - name: Run playwright tests
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run playwright  
        
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30        

