name: Build/Package Electron Apps for Windows/Mac/Linux

on:
  push:
    branches:
      - release

jobs:
  package-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'  

    - name: Install dependencies
      run: npm ci

    - name: Build Electron app for windows
      run: npx electron-forge make

  package-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'  

    - name: Install dependencies
      run: npm ci

    - name: Build Electron app for linux
      run: npx electron-forge make

